# Where things are
source:       .
destination:  _site

# Conversion
markdown:     kramdown
plugins:
  - jekyll-redirect-from

redirect_from:
  json: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
# Default
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
# This project
   - README.md
   - "**/README.md"
